<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2060eaaa-907d-40f2-afd1-5f68ae67a409</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_172_hon_chim_canh_cut_quy_hiem_bi_dan_on</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/main[1]/article[9]/header[1]/h2[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#post-28 .entry-title a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>