<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8ddb0435-eef1-487e-984a-43a81066c5db</elementGuidId>
    <imagePath></imagePath>
    <name>input_submit</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/main[1]/div[1]/ol[1]/li[2]/div[1]/form[1]/p[7]/input[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'submit')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>submit</value>
        <webElementGuid>1040f471-464d-4a55-bad2-540f53f3d7cb</webElementGuid>
    </webElementProperties>
</WebElementEntity>